

1.   Dos motos viajan a diferentes velocidades (**vel1** y **vel2**) y están distanciados por una distancia **dis**. La moto que se encuentra detrás lleva una velocidad mayor que la primera. Se pide realizar un script en python que solicite al usuario la distancia entre las motos en km y las velocidades de las mismas y con ello devolver en cuanto tiempo la moto 2 alcanzará a la moto 1.

In [ ]:
distancia = float(input("distancia entre las motos (km): "))
vel1 = float(input("Velocidad de la primera moto en km/h: "))
vel2 = float(input("Velocidad de la segunda moto en km/h: "))
if vel2 <= vel1:
    print("La moto 2 tiene que ir a más velocidad")
else:
    tiempo = distancia / (vel2 - vel1)

    print(f"La segunda moto llegará a la primera moto en {tiempo} horas")

2. El tutor de 2º ASIR esta organizando un viaje a Granada, y requiere determinar cuánto debe cobrar a cada alumne y cuánto debe pagar a la agencia de viajes. La forma de cobrar es la siguiente: si son 100 alumnos o más, el costo por cada alumno es de 65 euros; de 50 a 99 alumnos, el costo es de 70 euros, de 30 a 49, de 95 euros, y si son menos de 30, el costo de la guagua es de 4000 euros, sin importar el número de alumnos. Realice un script que permita determinar el pago a la compañía de guaguas y lo que debe pagar cada alumno por el viaje.

In [ ]:
numalus = int(input("Numero de alumnos: "))
if numalus >= 100:
  costoalum = 65
  total = numalus * costoalum
elif numalus >= 50:
  costoalum = 70
  total = numalus * costoalum
elif numalus >= 30:
  costoalum = 95
  total = numalus * costoalum
else:
  total = 4000
  costoalum = 0

print(f"El coste del viaje será de {total} €")
if costoalum > 0:
    print(f"Costo por alumno: {costoalum} €")
else:
    print("El costo es fijo, no se puede mostrar")

Numero de alumnos: 50
El coste del viaje será de 3500 €
Costo por alumno: 70 €


3. Crea un script que permita adivinar un número. La aplicación genera un número aleatorio del 1 al 100. A continuación va pidiendo números y va respondiendo si el número a adivinar es mayor o menor que el introducido, además de los intentos que te quedan (tienes 10 intentos para acertarlo).  El programa termina cuando se acierta el número (además te dice en cuantos  intentos lo has acertado), si se llega al limite de intentos te muestra el  número que había generado.

In [ ]:

import random

def adivina_numero():
    numero_secreto = random.randint(1, 100)
    intentos = 10

    print("¡Bienvenido al juego de adivinar el número!")
    print("He generado un número aleatorio entre 1 y 100.")

    while intentos > 0:
        try:
            intento = int(input(f"Intento {11 - intentos}: Introduce un número: "))
        except ValueError:
            print("Entrada inválida. Por favor, introduce un número entero.")
            continue

        if intento < numero_secreto:
            print("El número secreto es mayor.")
        elif intento > numero_secreto:
            print("El número secreto es menor.")
        else:
            print(f"¡Felicidades! Has acertado el número en {11 - intentos} intentos.")
            return

        intentos -= 1
        print(f"Te quedan {intentos} intentos.")

    print(f"Lo siento, has agotado tus intentos. El número secreto era {numero_secreto}.")

adivina_numero()


¡Bienvenido al juego de adivinar el número!
He generado un número aleatorio entre 1 y 100.
Intento 1: Introduce un número: 4
El número secreto es mayor.
Te quedan 9 intentos.
Intento 2: Introduce un número: 18
El número secreto es mayor.
Te quedan 8 intentos.
Intento 3: Introduce un número: 55
El número secreto es mayor.
Te quedan 7 intentos.
Intento 4: Introduce un número: 80
El número secreto es mayor.
Te quedan 6 intentos.
Intento 5: Introduce un número: 99
¡Felicidades! Has acertado el número en 5 intentos.


4. Realizar un script que pida una String por teclado que contenga espacios y devuelva el número de palabrás que contenga

In [ ]:
def contar_palabras(cadena):
  palabras = cadena.split()
  return len(palabras)

# Solicitar la cadena al usuario
cadena = input("Introduce una cadena de texto: ")

# Contar las palabras y mostrar el resultado
numero_palabras = contar_palabras(cadena)
print("El número de palabras en la cadena es:", numero_palabras)


5. Realiza un script que se le pasen 5 notas de un alumno por teclado (comprendidas entre 0 y 10). A continuación debe mostrar todas las notas, la nota media, la nota más alta que ha sacado y la menor.



In [1]:
notas = []
for i in range(5):
    while True:
        try:
            nota = float(input(f"Introduce la nota {i+1} (entre 0 y 10): "))
            if 0 <= nota <= 10:
                notas.append(nota)
                break
            else:
                print("Nota inválida. Introduce un valor entre 0 y 10.")
        except ValueError:
            print("Entrada inválida. Introduce un número.")

print("\nNotas introducidas:", notas)
media = sum(notas) / len(notas)
print("Nota media:", media)
nota_maxima = max(notas)
print("Nota más alta:", nota_maxima)
nota_minima = min(notas)
print("Nota más baja:", nota_minima)

Introduce la nota 1 (entre 0 y 10): 4
Introduce la nota 2 (entre 0 y 10): 5
Introduce la nota 3 (entre 0 y 10): 3
Introduce la nota 4 (entre 0 y 10): 4
Introduce la nota 5 (entre 0 y 10): 5

Notas introducidas: [4.0, 5.0, 3.0, 4.0, 5.0]
Nota media: 4.2
Nota más alta: 5.0
Nota más baja: 3.0


6. Realizar un script que cree una una tabla bidimensional de 5x5 y nombre 'diagonal'. La Componentes de la tabla en su diagonales deben de ser 1 y el resto 0. Se ha de mostrar el contenido de la tabla por pantalla.

In [4]:
import numpy as np

#Crear una matriz de 5x5 con ceros y la diagonal
diagonal = np.zeros((5, 5), dtype=int)
np.fill_diagonal(diagonal, 1)

#La muestro
print(diagonal)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


7. Crea un script que pida un número y cree un diccionario cuyas claves sean desde el número 1 hasta el número indicado, y los valores sean los cuadrados de las claves.



In [5]:
num = int(input("Introduce un número: "))

#creo el diccionario
diccionario = {i: i**2 for i in range(1, num + 1)}

#Lo muestro
print(diccionario)

Introduce un número: 20
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400}


8. Crea un script de una agenda en la que se guardan nombres y números de teléfono. En la agenda existirá un menú con las siguientes opciones:
 * **Añadir/modificar**: Nos pide un nombre. Si el nombre se encuentra en la agenda, debe mostrar el teléfono y, opcionalmente, permitir modificarlo si no es correcto. Si el nombre no se encuentra, debe permitir ingresar el teléfono correspondiente.
 * **Buscar**: Nos pide una cadena de caracteres, y nos muestras todos los contactos cuyos nombres comiencen por dicha cadena.
 * **Borrar**: Nos pide un nombre y si existe nos preguntará si queremos borrarlo de la agenda.
 * **Listar**: Nos muestra todos los contactos de la agenda.

  Implementar el script con un diccionario.

In [ ]:
agenda = {}

#menú
while True:
    print("\nAgenda de Contactos")
    print("1. Añadir contacto")
    print("2. Buscar contacto")
    print("3. Eliminar contacto")
    print("4. Mostrar todos los contactos")
    print("5. Salir")

    opcion = input("Elige una opción: ")

#añadir el contacto

    if opcion == '1':
        nombre = input("Introduce el nombre del contacto: ")
        telefono = input("Introduce el número de teléfono: ")
        if nombre in agenda:
            print("El contacto ya existe. Actualizando el número de teléfono.")
        agenda[nombre] = telefono
        print("Contacto añadido/actualizado.")

#buscar el contacto

    elif opcion == '2':
        nombre = input("Introduce el nombre del contacto a buscar: ")
        if nombre in agenda:
            print(f"El número de teléfono de {nombre} es {agenda[nombre]}")
        else:
            print("El contacto no existe en la agenda.")

#Eliminar un contacto

    elif opcion == '3':
        nombre = input("Introduce el nombre del contacto a eliminar: ")
        if nombre in agenda:
            del agenda[nombre]
            print("Contacto eliminado.")
        else:
            print("El contacto no existe en la agenda.")

#Mostrar los contactos

    elif opcion == '4':
        if agenda:
            print("Todos los contactos:")
            for nombre, telefono in agenda.items():
                print(f"{nombre}: {telefono}")
        else:
            print("La agenda está vacía.")

    elif opcion == '5':
        print("Saliendo del programa...")
        break

    else:
        print("Opción no válida. Por favor, elige una opción del 1 al 5.")

9. Crear un script que al introducir una fecha nos diga a que día juliano corresponde. El día juliano correspondiente a una fecha es un número entero que indica los días que han transcurrido desde el 1 de enero.Para ello debes de hacer las siguientes funciones:
 * **LeerFecha**: Lee por teclado el día, mes y el año.
 * **DiasDelMes**: Recibe un mes y un año y devuelve el número de días
 * **EsBisiesto**: Recibido un año nos dice si es bisiesto o no.
 * **Calcular_Dia_Juliano**: Recibe una fecha y nos devuelve el día juliano.

In [7]:
#declaro la funcion para leer la fecha
def leerfecha():
    dia = int(input("Introduce el día: "))
    mes = int(input("Introduce el mes: "))
    año = int(input("Introduce el año: "))
    return dia, mes, año

#a ver si es biciesto

def esbisiesto(año):
    return año % 4 == 0 and (año % 100 != 0 or año % 400 == 0)

#calculo de los días del mes

def diasdelmes(mes, año):
    if mes in [1, 3, 5, 7, 8, 10, 12]:
        return 31
    elif mes == 2:
        if esbisiesto(año):
            return 29
        else:
            return 28
    else:
        return 30

#calcular el día juliano

def calcular_dia_juliano(dia, mes, año):
    dias_juliano = 0
    for m in range(1, mes):
        dias_juliano += diasdelmes(m, año)
    dias_juliano += dia
    return dias_juliano

dia, mes, año = leerfecha()

if mes < 1 or mes > 12:
    print("Mes no válido.")
elif dia < 1 or dia > diasdelmes(mes, año):
    print("Día no válido para el mes y año dados.")
else:
    dia_juliano = calcular_dia_juliano(dia, mes, año)
    print(f"El día juliano correspondiente a {dia}/{mes}/{año} es {dia_juliano}.")

Introduce el día: 30
Introduce el mes: 08
Introduce el año: 1995
El día juliano correspondiente a 30/8/1995 es 242.



10. Función CalcularMCD: Recibe dos números y devuelve el MCD utilizando el método de Euclides.
El método de Euclides es el siguiente:
 * Se divide el número mayor entre el menor.
 * Si la división es exacta, el divisor es el MCD.
 * Si la división no es exacta, dividimos el divisor entre el resto obtenido y se continúa de esta forma hasta obtener una división exacta, siendo el último divisor el MCD.


In [9]:
def calcularmcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a
num1 = int(input("Introduce el primer número: "))
num2 = int(input("Introduce el segundo número: "))

mcd = calcularmcd(num1, num2)
print(f"El MCD de {num1} y {num2} es {mcd}.")

Introduce el primer número: 12
Introduce el segundo número: 6
El MCD de 12 y 6 es 6.
